### ISSUE TITLE
core.plugin.PluginException: 'module' object has no attribute 'FuzzManager'

### ISSUE THREAD

**Issue by joxeankoret** [MozillaSecurity/quokka#9]
Hi,

I'm trying to use quokka for testing but it always fails to me with a message like the following one:

```
Traceback (most recent call last):
  File "quokka.py", line 130, in <module>
    sys.exit(QuokkaCommandLine().main())
  File "quokka.py", line 110, in main
    quokka.run_plugin()
  File "/home/quokka/quokka/core/quokka.py", line 63, in run_plugin
    self.attach_loggers(self.conf.loggers)
  File "/home/quokka/quokka/core/quokka.py", line 128, in attach_loggers
    logger_class = self.import_plugin_class('core.loggers.' + logger_class)
  File "/home/quokka/quokka/core/quokka.py", line 44, in import_plugin_class
    raise PluginException(msg)
core.plugin.PluginException: 'module' object has no attribute 'FuzzManager'
```

I git-cloned https://github.com/MozillaSecurity/FuzzManager in the "utils" sub-directory I just created but i fails anyway. Am I doing something wrong?

Thanks!

**Comment by rc0r** [comment]
I suspect this is an error in `quokka.json`. Try to use:

```
{
      "class": "fuzzmanager.FuzzManagerLogger",
      "kargs": {
        "binary": ""
      }
}
```
as logger class for `FuzzManager`.
